// pip.constants.js — All shared data for Placement Intelligence Platform

export const COMPANIES = {
  Amazon: {
    pkg: "₹26 LPA",
    rate: "4%",
    branches: ["CSE", "IT"],
    rounds: [
      "OA (90 min)",
      "DSA Round 1",
      "DSA Round 2",
      "System Design",
      "Bar Raiser",
    ],
    topics: {
      Arrays: 28,
      Graphs: 22,
      "Dynamic Programming": 19,
      Trees: 15,
      "Sliding Window": 10,
      Strings: 6,
    },
    hotQs: [
      "Two Sum",
      "LRU Cache",
      "Number of Islands",
      "Merge Intervals",
      "Longest Substring Without Repeating",
      "Word Ladder",
      "Trapping Rain Water",
      "Median of Data Stream",
    ],
    color: "#FF9900",
    logo: "A",
  },
  Google: {
    pkg: "₹40 LPA",
    rate: "2%",
    branches: ["CSE", "IT", "ECE"],
    rounds: [
      "Phone Screen",
      "Coding Round 1",
      "Coding Round 2",
      "System Design",
      "Googleyness",
    ],
    topics: {
      "Dynamic Programming": 30,
      Graphs: 25,
      Trees: 20,
      Arrays: 15,
      "Math/Number Theory": 10,
    },
    hotQs: [
      "Longest Increasing Subsequence",
      "Word Break",
      "Alien Dictionary",
      "Course Schedule",
      "Serialize/Deserialize Tree",
      "Minimum Window Substring",
      "Jump Game II",
    ],
    color: "#4285F4",
    logo: "G",
  },
  Microsoft: {
    pkg: "₹22 LPA",
    rate: "5%",
    branches: ["CSE", "IT"],
    rounds: [
      "OA",
      "Technical Round 1",
      "Technical Round 2",
      "Design Round",
      "HR",
    ],
    topics: {
      Trees: 30,
      "Linked Lists": 20,
      Arrays: 18,
      Strings: 16,
      "Dynamic Programming": 10,
      Graphs: 6,
    },
    hotQs: [
      "Reverse Linked List",
      "Level Order Traversal",
      "Clone Graph",
      "Validate BST",
      "Spiral Matrix",
      "Decode Ways",
      "Max Subarray",
    ],
    color: "#00A4EF",
    logo: "M",
  },
  Flipkart: {
    pkg: "₹18 LPA",
    rate: "6%",
    branches: ["CSE", "IT", "ECE", "EEE"],
    rounds: ["Machine Coding", "DSA Round", "System Design", "Hiring Manager"],
    topics: {
      Arrays: 30,
      "Linked Lists": 22,
      Trees: 18,
      Greedy: 15,
      Strings: 10,
      Heaps: 5,
    },
    hotQs: [
      "Smallest Positive Missing",
      "Flatten Linked List",
      "Connect Nodes at Same Level",
      "Min Platforms",
      "Largest Rectangle Histogram",
    ],
    color: "#F7E600",
    logo: "F",
  },
  Uber: {
    pkg: "₹32 LPA",
    rate: "3%",
    branches: ["CSE", "IT"],
    rounds: ["HackerRank OA", "Technical Phone", "Onsite x4"],
    topics: {
      Graphs: 32,
      "Dynamic Programming": 22,
      "Sliding Window": 18,
      Arrays: 14,
      "Bit Manipulation": 8,
      Design: 6,
    },
    hotQs: [
      "Surge Pricing Simulation",
      "Dijkstra Shortest Path",
      "Rate Limiter Design",
      "Longest Consecutive Sequence",
      "K Closest Points",
    ],
    color: "#000000",
    logo: "U",
  },
  Adobe: {
    pkg: "₹20 LPA",
    rate: "7%",
    branches: ["CSE", "IT", "ECE"],
    rounds: ["OA", "DSA Round", "CS Fundamentals", "HR"],
    topics: {
      Arrays: 32,
      Strings: 25,
      Trees: 18,
      Recursion: 12,
      "Dynamic Programming": 8,
      Heaps: 5,
    },
    hotQs: [
      "Stock Buy Sell",
      "Anagram Check",
      "Longest Common Prefix",
      "Power Function",
      "Rotate Image",
      "Next Permutation",
    ],
    color: "#FF0000",
    logo: "Ad",
  },
};

// Seed data — shown before any user submissions exist
export const SEED_EXPERIENCES = [
  {
    id: "seed_1",
    company: "Amazon",
    role: "SDE-1",
    college: "NIT Trichy",
    rounds: 4,
    selected: true,
    date: "2025-02-10",
    story:
      "Round 1 had two pointer + sliding window. Round 2 was pure DP (0/1 knapsack variant). System design was URL shortener. Final bar raiser focused on leadership principles.",
    difficulty: "Hard",
    authorName: "",
    socialLink: "",
    isSeed: true,
  },
  {
    id: "seed_2",
    company: "Google",
    role: "SDE-1",
    college: "IIT Bombay",
    rounds: 5,
    selected: true,
    date: "2025-01-25",
    story:
      "All rounds were DSA heavy. Got graph traversal in first two rounds. System Design was Google Docs. Googleyness round asked about conflict resolution.",
    difficulty: "Very Hard",
    authorName: "",
    socialLink: "",
    isSeed: true,
  },
  {
    id: "seed_3",
    company: "Microsoft",
    role: "SDE-1",
    college: "VIT Vellore",
    rounds: 4,
    selected: false,
    date: "2025-02-18",
    story:
      "Focused heavily on trees — BST questions in both technical rounds. Got rejected in design round for not knowing distributed systems basics.",
    difficulty: "Medium",
    authorName: "",
    socialLink: "",
    isSeed: true,
  },
  {
    id: "seed_4",
    company: "Flipkart",
    role: "SDE-1",
    college: "BITS Pilani",
    rounds: 3,
    selected: true,
    date: "2025-02-05",
    story:
      "Machine coding round had 90 mins to build a parking lot system. DSA was greedy + arrays. System design was cab booking.",
    difficulty: "Medium",
    authorName: "",
    socialLink: "",
    isSeed: true,
  },
  {
    id: "seed_5",
    company: "Uber",
    role: "SDE-2",
    college: "IIT Delhi",
    rounds: 5,
    selected: true,
    date: "2025-01-15",
    story:
      "Heavy graphs focus — got Dijkstra and modified BFS. Rate limiter design in system design round. Great culture fit round at end.",
    difficulty: "Hard",
    authorName: "",
    socialLink: "",
    isSeed: true,
  },
  {
    id: "seed_6",
    company: "Adobe",
    role: "SDE-1",
    college: "DTU Delhi",
    rounds: 3,
    selected: true,
    date: "2025-01-30",
    story:
      "Round 1 was a 1-hour OA on HackerRank — mostly arrays and strings. Round 2 went deep on recursion and backtracking. Final round was CS fundamentals (OS + DBMS) and HR. Good experience overall.",
    difficulty: "Medium",
    authorName: "",
    socialLink: "",
    isSeed: true,
  },
];

export const ROLES = [
  "SDE-1",
  "SDE-2",
  "Data Analyst",
  "ML Engineer",
  "Product Manager",
];
export const DIFFICULTIES = ["Easy", "Medium", "Hard", "Very Hard"];

export const EXPERIENCES_KEY = "pip_experiences_v2";
export const SETUP_KEY = "pip_setup_v2";
export const SOLVED_KEY_PREFIX = "pip_solved_";
