// pip.questions.js — Master questions database
// Tags: company, difficulty, frequency, pattern, topic, leetcodeId, title, url

export const PATTERNS = [
  "Two Pointers",
  "Sliding Window",
  "Binary Search",
  "BFS/DFS",
  "Dynamic Programming",
  "Backtracking",
  "Greedy",
  "Heap / Priority Queue",
  "Stack / Monotonic Stack",
  "Hashing",
  "Recursion / Divide & Conquer",
  "Linked List",
  "Tree Traversal",
  "Graph Algorithms",
  "Bit Manipulation",
  "Prefix Sum",
  "Trie",
  "Union Find",
  "Sorting",
  "Math",
];

export const TOPICS = [
  "Arrays",
  "Strings",
  "Linked List",
  "Trees",
  "Graphs",
  "Dynamic Programming",
  "Sliding Window",
  "Two Pointers",
  "Backtracking",
  "Heap",
  "Stack",
  "Queue",
  "Binary Search",
  "Bit Manipulation",
  "Math",
  "Trie",
  "Greedy",
];

// frequency: 1-5 (5 = asked very frequently)
// difficulty: "Easy" | "Medium" | "Hard"
export const QUESTIONS = [
  // ─── ARRAYS ───
  {
    id: "q001",
    title: "Two Sum",
    leetcodeId: 1,
    url: "https://leetcode.com/problems/two-sum/",
    topic: "Arrays",
    pattern: "Hashing",
    difficulty: "Easy",
    frequency: 5,
    companies: [
      "Amazon",
      "Google",
      "Microsoft",
      "Meta",
      "Apple",
      "Adobe",
      "Flipkart",
    ],
    tags: ["classic", "interview-must"],
  },
  {
    id: "q002",
    title: "Best Time to Buy and Sell Stock",
    leetcodeId: 121,
    url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    topic: "Arrays",
    pattern: "Sliding Window",
    difficulty: "Easy",
    frequency: 5,
    companies: [
      "Amazon",
      "Google",
      "Microsoft",
      "Meta",
      "Goldman Sachs",
      "Morgan Stanley",
    ],
    tags: ["greedy", "classic"],
  },
  {
    id: "q003",
    title: "Contains Duplicate",
    leetcodeId: 217,
    url: "https://leetcode.com/problems/contains-duplicate/",
    topic: "Arrays",
    pattern: "Hashing",
    difficulty: "Easy",
    frequency: 4,
    companies: ["Amazon", "Microsoft", "Adobe"],
    tags: ["sorting-alternative"],
  },
  {
    id: "q004",
    title: "Product of Array Except Self",
    leetcodeId: 238,
    url: "https://leetcode.com/problems/product-of-array-except-self/",
    topic: "Arrays",
    pattern: "Prefix Sum",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Apple"],
    tags: ["no-division", "must-do"],
  },
  {
    id: "q005",
    title: "Maximum Subarray",
    leetcodeId: 53,
    url: "https://leetcode.com/problems/maximum-subarray/",
    topic: "Arrays",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Flipkart", "Adobe"],
    tags: ["kadane", "classic"],
  },
  {
    id: "q006",
    title: "Maximum Product Subarray",
    leetcodeId: 152,
    url: "https://leetcode.com/problems/maximum-product-subarray/",
    topic: "Arrays",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["kadane-variant"],
  },
  {
    id: "q007",
    title: "Find Minimum in Rotated Sorted Array",
    leetcodeId: 153,
    url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    topic: "Arrays",
    pattern: "Binary Search",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["rotated-array"],
  },
  {
    id: "q008",
    title: "Search in Rotated Sorted Array",
    leetcodeId: 33,
    url: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    topic: "Arrays",
    pattern: "Binary Search",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Apple"],
    tags: ["rotated-array", "must-do"],
  },
  {
    id: "q009",
    title: "3Sum",
    leetcodeId: 15,
    url: "https://leetcode.com/problems/3sum/",
    topic: "Arrays",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["sorting", "classic"],
  },
  {
    id: "q010",
    title: "Container With Most Water",
    leetcodeId: 11,
    url: "https://leetcode.com/problems/container-with-most-water/",
    topic: "Arrays",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["greedy", "classic"],
  },
  {
    id: "q011",
    title: "Trapping Rain Water",
    leetcodeId: 42,
    url: "https://leetcode.com/problems/trapping-rain-water/",
    topic: "Arrays",
    pattern: "Two Pointers",
    difficulty: "Hard",
    frequency: 5,
    companies: [
      "Amazon",
      "Google",
      "Microsoft",
      "Meta",
      "Goldman Sachs",
      "Adobe",
    ],
    tags: ["stack-alt", "must-do"],
  },
  {
    id: "q012",
    title: "Merge Intervals",
    leetcodeId: 56,
    url: "https://leetcode.com/problems/merge-intervals/",
    topic: "Arrays",
    pattern: "Sorting",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["intervals", "must-do"],
  },
  {
    id: "q013",
    title: "Insert Interval",
    leetcodeId: 57,
    url: "https://leetcode.com/problems/insert-interval/",
    topic: "Arrays",
    pattern: "Sorting",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Meta"],
    tags: ["intervals"],
  },
  {
    id: "q014",
    title: "Rotate Array",
    leetcodeId: 189,
    url: "https://leetcode.com/problems/rotate-array/",
    topic: "Arrays",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Microsoft", "Adobe"],
    tags: ["in-place"],
  },
  {
    id: "q015",
    title: "Jump Game",
    leetcodeId: 55,
    url: "https://leetcode.com/problems/jump-game/",
    topic: "Arrays",
    pattern: "Greedy",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["greedy"],
  },
  {
    id: "q016",
    title: "Jump Game II",
    leetcodeId: 45,
    url: "https://leetcode.com/problems/jump-game-ii/",
    topic: "Arrays",
    pattern: "Greedy",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["greedy"],
  },
  {
    id: "q017",
    title: "Set Matrix Zeroes",
    leetcodeId: 73,
    url: "https://leetcode.com/problems/set-matrix-zeroes/",
    topic: "Arrays",
    pattern: "Hashing",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Microsoft", "Adobe", "Flipkart"],
    tags: ["matrix", "in-place"],
  },
  {
    id: "q018",
    title: "Spiral Matrix",
    leetcodeId: 54,
    url: "https://leetcode.com/problems/spiral-matrix/",
    topic: "Arrays",
    pattern: "Sorting",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["matrix", "simulation"],
  },

  // ─── STRINGS ───
  {
    id: "q019",
    title: "Longest Substring Without Repeating Characters",
    leetcodeId: 3,
    url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    topic: "Strings",
    pattern: "Sliding Window",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe", "Flipkart"],
    tags: ["classic", "must-do"],
  },
  {
    id: "q020",
    title: "Longest Repeating Character Replacement",
    leetcodeId: 424,
    url: "https://leetcode.com/problems/longest-repeating-character-replacement/",
    topic: "Strings",
    pattern: "Sliding Window",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["sliding-window"],
  },
  {
    id: "q021",
    title: "Minimum Window Substring",
    leetcodeId: 76,
    url: "https://leetcode.com/problems/minimum-window-substring/",
    topic: "Strings",
    pattern: "Sliding Window",
    difficulty: "Hard",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["must-do", "hard"],
  },
  {
    id: "q022",
    title: "Valid Anagram",
    leetcodeId: 242,
    url: "https://leetcode.com/problems/valid-anagram/",
    topic: "Strings",
    pattern: "Hashing",
    difficulty: "Easy",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["frequency-count"],
  },
  {
    id: "q023",
    title: "Group Anagrams",
    leetcodeId: 49,
    url: "https://leetcode.com/problems/group-anagrams/",
    topic: "Strings",
    pattern: "Hashing",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["classic", "must-do"],
  },
  {
    id: "q024",
    title: "Valid Parentheses",
    leetcodeId: 20,
    url: "https://leetcode.com/problems/valid-parentheses/",
    topic: "Strings",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Easy",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe", "Flipkart"],
    tags: ["stack", "classic"],
  },
  {
    id: "q025",
    title: "Palindromic Substrings",
    leetcodeId: 647,
    url: "https://leetcode.com/problems/palindromic-substrings/",
    topic: "Strings",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["expand-around-center"],
  },
  {
    id: "q026",
    title: "Longest Palindromic Substring",
    leetcodeId: 5,
    url: "https://leetcode.com/problems/longest-palindromic-substring/",
    topic: "Strings",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["expand-center", "must-do"],
  },
  {
    id: "q027",
    title: "Encode and Decode Strings",
    leetcodeId: 271,
    url: "https://leetcode.com/problems/encode-and-decode-strings/",
    topic: "Strings",
    pattern: "Hashing",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Google", "Meta"],
    tags: ["design"],
  },
  {
    id: "q028",
    title: "Reverse Words in a String",
    leetcodeId: 151,
    url: "https://leetcode.com/problems/reverse-words-in-a-string/",
    topic: "Strings",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Microsoft", "Adobe"],
    tags: ["in-place"],
  },

  // ─── LINKED LIST ───
  {
    id: "q029",
    title: "Reverse Linked List",
    leetcodeId: 206,
    url: "https://leetcode.com/problems/reverse-linked-list/",
    topic: "Linked List",
    pattern: "Linked List",
    difficulty: "Easy",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe", "Flipkart"],
    tags: ["classic", "must-do"],
  },
  {
    id: "q030",
    title: "Linked List Cycle",
    leetcodeId: 141,
    url: "https://leetcode.com/problems/linked-list-cycle/",
    topic: "Linked List",
    pattern: "Two Pointers",
    difficulty: "Easy",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["floyd-cycle", "must-do"],
  },
  {
    id: "q031",
    title: "Merge Two Sorted Lists",
    leetcodeId: 21,
    url: "https://leetcode.com/problems/merge-two-sorted-lists/",
    topic: "Linked List",
    pattern: "Linked List",
    difficulty: "Easy",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["classic"],
  },
  {
    id: "q032",
    title: "Merge K Sorted Lists",
    leetcodeId: 23,
    url: "https://leetcode.com/problems/merge-k-sorted-lists/",
    topic: "Linked List",
    pattern: "Heap / Priority Queue",
    difficulty: "Hard",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["heap", "must-do"],
  },
  {
    id: "q033",
    title: "Remove Nth Node From End of List",
    leetcodeId: 19,
    url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    topic: "Linked List",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["two-pass-or-one"],
  },
  {
    id: "q034",
    title: "Reorder List",
    leetcodeId: 143,
    url: "https://leetcode.com/problems/reorder-list/",
    topic: "Linked List",
    pattern: "Linked List",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["in-place"],
  },
  {
    id: "q035",
    title: "Find the Duplicate Number",
    leetcodeId: 287,
    url: "https://leetcode.com/problems/find-the-duplicate-number/",
    topic: "Linked List",
    pattern: "Two Pointers",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Meta"],
    tags: ["floyd-cycle", "bit-manipulation-alt"],
  },
  {
    id: "q036",
    title: "LRU Cache",
    leetcodeId: 146,
    url: "https://leetcode.com/problems/lru-cache/",
    topic: "Linked List",
    pattern: "Hashing",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["design", "must-do"],
  },

  // ─── TREES ───
  {
    id: "q037",
    title: "Invert Binary Tree",
    leetcodeId: 226,
    url: "https://leetcode.com/problems/invert-binary-tree/",
    topic: "Trees",
    pattern: "Tree Traversal",
    difficulty: "Easy",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["recursive"],
  },
  {
    id: "q038",
    title: "Maximum Depth of Binary Tree",
    leetcodeId: 104,
    url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    topic: "Trees",
    pattern: "BFS/DFS",
    difficulty: "Easy",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["classic"],
  },
  {
    id: "q039",
    title: "Same Tree",
    leetcodeId: 100,
    url: "https://leetcode.com/problems/same-tree/",
    topic: "Trees",
    pattern: "Tree Traversal",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Microsoft"],
    tags: ["recursive"],
  },
  {
    id: "q040",
    title: "Subtree of Another Tree",
    leetcodeId: 572,
    url: "https://leetcode.com/problems/subtree-of-another-tree/",
    topic: "Trees",
    pattern: "Tree Traversal",
    difficulty: "Easy",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["recursive"],
  },
  {
    id: "q041",
    title: "Lowest Common Ancestor of BST",
    leetcodeId: 235,
    url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    topic: "Trees",
    pattern: "Tree Traversal",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["BST", "must-do"],
  },
  {
    id: "q042",
    title: "Binary Tree Level Order Traversal",
    leetcodeId: 102,
    url: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    topic: "Trees",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["BFS", "must-do"],
  },
  {
    id: "q043",
    title: "Binary Tree Right Side View",
    leetcodeId: 199,
    url: "https://leetcode.com/problems/binary-tree-right-side-view/",
    topic: "Trees",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Meta"],
    tags: ["BFS"],
  },
  {
    id: "q044",
    title: "Count Good Nodes in Binary Tree",
    leetcodeId: 1448,
    url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree/",
    topic: "Trees",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["DFS"],
  },
  {
    id: "q045",
    title: "Validate Binary Search Tree",
    leetcodeId: 98,
    url: "https://leetcode.com/problems/validate-binary-search-tree/",
    topic: "Trees",
    pattern: "Tree Traversal",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["BST", "must-do"],
  },
  {
    id: "q046",
    title: "Kth Smallest Element in a BST",
    leetcodeId: 230,
    url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/",
    topic: "Trees",
    pattern: "Tree Traversal",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["inorder"],
  },
  {
    id: "q047",
    title: "Construct Binary Tree from Preorder and Inorder",
    leetcodeId: 105,
    url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/",
    topic: "Trees",
    pattern: "Recursion / Divide & Conquer",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["recursion"],
  },
  {
    id: "q048",
    title: "Binary Tree Maximum Path Sum",
    leetcodeId: 124,
    url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/",
    topic: "Trees",
    pattern: "BFS/DFS",
    difficulty: "Hard",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["DFS", "must-do", "hard"],
  },
  {
    id: "q049",
    title: "Serialize and Deserialize Binary Tree",
    leetcodeId: 297,
    url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    topic: "Trees",
    pattern: "BFS/DFS",
    difficulty: "Hard",
    frequency: 4,
    companies: ["Amazon", "Google", "Meta"],
    tags: ["design", "hard"],
  },

  // ─── GRAPHS ───
  {
    id: "q050",
    title: "Number of Islands",
    leetcodeId: 200,
    url: "https://leetcode.com/problems/number-of-islands/",
    topic: "Graphs",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe", "Flipkart"],
    tags: ["grid-DFS", "must-do"],
  },
  {
    id: "q051",
    title: "Clone Graph",
    leetcodeId: 133,
    url: "https://leetcode.com/problems/clone-graph/",
    topic: "Graphs",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["DFS", "hashing"],
  },
  {
    id: "q052",
    title: "Max Area of Island",
    leetcodeId: 695,
    url: "https://leetcode.com/problems/max-area-of-island/",
    topic: "Graphs",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["grid-DFS"],
  },
  {
    id: "q053",
    title: "Pacific Atlantic Water Flow",
    leetcodeId: 417,
    url: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    topic: "Graphs",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google"],
    tags: ["multi-source-BFS"],
  },
  {
    id: "q054",
    title: "Course Schedule",
    leetcodeId: 207,
    url: "https://leetcode.com/problems/course-schedule/",
    topic: "Graphs",
    pattern: "Graph Algorithms",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["topological-sort", "cycle-detection", "must-do"],
  },
  {
    id: "q055",
    title: "Course Schedule II",
    leetcodeId: 210,
    url: "https://leetcode.com/problems/course-schedule-ii/",
    topic: "Graphs",
    pattern: "Graph Algorithms",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["topological-sort"],
  },
  {
    id: "q056",
    title: "Number of Connected Components in Graph",
    leetcodeId: 323,
    url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/",
    topic: "Graphs",
    pattern: "Union Find",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["union-find"],
  },
  {
    id: "q057",
    title: "Word Ladder",
    leetcodeId: 127,
    url: "https://leetcode.com/problems/word-ladder/",
    topic: "Graphs",
    pattern: "BFS/DFS",
    difficulty: "Hard",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["BFS", "hard"],
  },
  {
    id: "q058",
    title: "Alien Dictionary",
    leetcodeId: 269,
    url: "https://leetcode.com/problems/alien-dictionary/",
    topic: "Graphs",
    pattern: "Graph Algorithms",
    difficulty: "Hard",
    frequency: 4,
    companies: ["Amazon", "Google", "Meta"],
    tags: ["topological-sort", "hard"],
  },
  {
    id: "q059",
    title: "Rotting Oranges",
    leetcodeId: 994,
    url: "https://leetcode.com/problems/rotting-oranges/",
    topic: "Graphs",
    pattern: "BFS/DFS",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Flipkart"],
    tags: ["multi-source-BFS"],
  },
  {
    id: "q060",
    title: "Network Delay Time",
    leetcodeId: 743,
    url: "https://leetcode.com/problems/network-delay-time/",
    topic: "Graphs",
    pattern: "Graph Algorithms",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["dijkstra"],
  },

  // ─── DYNAMIC PROGRAMMING ───
  {
    id: "q061",
    title: "Climbing Stairs",
    leetcodeId: 70,
    url: "https://leetcode.com/problems/climbing-stairs/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Easy",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["fibonacci", "classic"],
  },
  {
    id: "q062",
    title: "Coin Change",
    leetcodeId: 322,
    url: "https://leetcode.com/problems/coin-change/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["unbounded-knapsack", "must-do"],
  },
  {
    id: "q063",
    title: "Longest Increasing Subsequence",
    leetcodeId: 300,
    url: "https://leetcode.com/problems/longest-increasing-subsequence/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["LIS", "must-do"],
  },
  {
    id: "q064",
    title: "Longest Common Subsequence",
    leetcodeId: 1143,
    url: "https://leetcode.com/problems/longest-common-subsequence/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["LCS", "must-do"],
  },
  {
    id: "q065",
    title: "Word Break",
    leetcodeId: 139,
    url: "https://leetcode.com/problems/word-break/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["must-do"],
  },
  {
    id: "q066",
    title: "Combination Sum IV",
    leetcodeId: 377,
    url: "https://leetcode.com/problems/combination-sum-iv/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["unbounded-knapsack"],
  },
  {
    id: "q067",
    title: "House Robber",
    leetcodeId: 198,
    url: "https://leetcode.com/problems/house-robber/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["classic", "must-do"],
  },
  {
    id: "q068",
    title: "House Robber II",
    leetcodeId: 213,
    url: "https://leetcode.com/problems/house-robber-ii/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["circular"],
  },
  {
    id: "q069",
    title: "Decode Ways",
    leetcodeId: 91,
    url: "https://leetcode.com/problems/decode-ways/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["fibonacci-variant"],
  },
  {
    id: "q070",
    title: "Unique Paths",
    leetcodeId: 62,
    url: "https://leetcode.com/problems/unique-paths/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["grid-DP"],
  },
  {
    id: "q071",
    title: "Jump Game",
    leetcodeId: 55,
    url: "https://leetcode.com/problems/jump-game/",
    topic: "Dynamic Programming",
    pattern: "Greedy",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["greedy"],
  },
  {
    id: "q072",
    title: "Edit Distance",
    leetcodeId: 72,
    url: "https://leetcode.com/problems/edit-distance/",
    topic: "Dynamic Programming",
    pattern: "Dynamic Programming",
    difficulty: "Hard",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["2D-DP", "must-do"],
  },
  {
    id: "q073",
    title: "Burst Balloons",
    leetcodeId: 312,
    url: "https://leetcode.com/problems/burst-balloons/",
    topic: "Dynamic Programming",
    pattern: "Recursion / Divide & Conquer",
    difficulty: "Hard",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["interval-DP"],
  },

  // ─── SLIDING WINDOW ───
  {
    id: "q074",
    title: "Sliding Window Maximum",
    leetcodeId: 239,
    url: "https://leetcode.com/problems/sliding-window-maximum/",
    topic: "Sliding Window",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Hard",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["deque", "monotonic", "must-do"],
  },
  {
    id: "q075",
    title: "Permutation in String",
    leetcodeId: 567,
    url: "https://leetcode.com/problems/permutation-in-string/",
    topic: "Sliding Window",
    pattern: "Sliding Window",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["frequency-match"],
  },
  {
    id: "q076",
    title: "Fruit Into Baskets",
    leetcodeId: 904,
    url: "https://leetcode.com/problems/fruit-into-baskets/",
    topic: "Sliding Window",
    pattern: "Sliding Window",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["at-most-k"],
  },
  {
    id: "q077",
    title: "Subarray Sum Equals K",
    leetcodeId: 560,
    url: "https://leetcode.com/problems/subarray-sum-equals-k/",
    topic: "Sliding Window",
    pattern: "Prefix Sum",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["prefix-sum", "must-do"],
  },

  // ─── HEAP ───
  {
    id: "q078",
    title: "Find Median from Data Stream",
    leetcodeId: 295,
    url: "https://leetcode.com/problems/find-median-from-data-stream/",
    topic: "Heap",
    pattern: "Heap / Priority Queue",
    difficulty: "Hard",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["two-heaps", "must-do"],
  },
  {
    id: "q079",
    title: "Top K Frequent Elements",
    leetcodeId: 347,
    url: "https://leetcode.com/problems/top-k-frequent-elements/",
    topic: "Heap",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["bucket-sort-alt", "must-do"],
  },
  {
    id: "q080",
    title: "Kth Largest Element in Array",
    leetcodeId: 215,
    url: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    topic: "Heap",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Flipkart"],
    tags: ["quickselect-alt", "must-do"],
  },
  {
    id: "q081",
    title: "Task Scheduler",
    leetcodeId: 621,
    url: "https://leetcode.com/problems/task-scheduler/",
    topic: "Heap",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["greedy", "frequency"],
  },
  {
    id: "q082",
    title: "Design Twitter",
    leetcodeId: 355,
    url: "https://leetcode.com/problems/design-twitter/",
    topic: "Heap",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Meta", "Amazon"],
    tags: ["design", "OOP"],
  },

  // ─── BACKTRACKING ───
  {
    id: "q083",
    title: "Combination Sum",
    leetcodeId: 39,
    url: "https://leetcode.com/problems/combination-sum/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["classic", "must-do"],
  },
  {
    id: "q084",
    title: "Word Search",
    leetcodeId: 79,
    url: "https://leetcode.com/problems/word-search/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["grid-backtrack", "must-do"],
  },
  {
    id: "q085",
    title: "Subsets",
    leetcodeId: 78,
    url: "https://leetcode.com/problems/subsets/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["power-set"],
  },
  {
    id: "q086",
    title: "Permutations",
    leetcodeId: 46,
    url: "https://leetcode.com/problems/permutations/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["classic"],
  },
  {
    id: "q087",
    title: "Letter Combinations of Phone Number",
    leetcodeId: 17,
    url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["classic"],
  },
  {
    id: "q088",
    title: "Palindrome Partitioning",
    leetcodeId: 131,
    url: "https://leetcode.com/problems/palindrome-partitioning/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["backtrack+DP"],
  },
  {
    id: "q089",
    title: "N-Queens",
    leetcodeId: 51,
    url: "https://leetcode.com/problems/n-queens/",
    topic: "Backtracking",
    pattern: "Backtracking",
    difficulty: "Hard",
    frequency: 3,
    companies: ["Google", "Meta"],
    tags: ["classic", "hard"],
  },

  // ─── STACK ───
  {
    id: "q090",
    title: "Daily Temperatures",
    leetcodeId: 739,
    url: "https://leetcode.com/problems/daily-temperatures/",
    topic: "Stack",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["monotonic-stack", "must-do"],
  },
  {
    id: "q091",
    title: "Car Fleet",
    leetcodeId: 853,
    url: "https://leetcode.com/problems/car-fleet/",
    topic: "Stack",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["monotonic"],
  },
  {
    id: "q092",
    title: "Largest Rectangle in Histogram",
    leetcodeId: 84,
    url: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    topic: "Stack",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Hard",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["monotonic-stack", "must-do", "hard"],
  },
  {
    id: "q093",
    title: "Min Stack",
    leetcodeId: 155,
    url: "https://leetcode.com/problems/min-stack/",
    topic: "Stack",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Adobe"],
    tags: ["design", "must-do"],
  },
  {
    id: "q094",
    title: "Next Greater Element I",
    leetcodeId: 496,
    url: "https://leetcode.com/problems/next-greater-element-i/",
    topic: "Stack",
    pattern: "Stack / Monotonic Stack",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Microsoft"],
    tags: ["monotonic-stack"],
  },

  // ─── BINARY SEARCH ───
  {
    id: "q095",
    title: "Binary Search",
    leetcodeId: 704,
    url: "https://leetcode.com/problems/binary-search/",
    topic: "Binary Search",
    pattern: "Binary Search",
    difficulty: "Easy",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["classic"],
  },
  {
    id: "q096",
    title: "Median of Two Sorted Arrays",
    leetcodeId: 4,
    url: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    topic: "Binary Search",
    pattern: "Binary Search",
    difficulty: "Hard",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["O(log(m+n))", "hard", "must-do"],
  },
  {
    id: "q097",
    title: "Time Based Key-Value Store",
    leetcodeId: 981,
    url: "https://leetcode.com/problems/time-based-key-value-store/",
    topic: "Binary Search",
    pattern: "Binary Search",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["design"],
  },
  {
    id: "q098",
    title: "Koko Eating Bananas",
    leetcodeId: 875,
    url: "https://leetcode.com/problems/koko-eating-bananas/",
    topic: "Binary Search",
    pattern: "Binary Search",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google"],
    tags: ["binary-search-answer"],
  },

  // ─── TRIE ───
  {
    id: "q099",
    title: "Implement Trie",
    leetcodeId: 208,
    url: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    topic: "Trie",
    pattern: "Trie",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta"],
    tags: ["design", "must-do"],
  },
  {
    id: "q100",
    title: "Design Add and Search Words Data Structure",
    leetcodeId: 211,
    url: "https://leetcode.com/problems/design-add-and-search-words-data-structure/",
    topic: "Trie",
    pattern: "Trie",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["design", "DFS"],
  },
  {
    id: "q101",
    title: "Word Search II",
    leetcodeId: 212,
    url: "https://leetcode.com/problems/word-search-ii/",
    topic: "Trie",
    pattern: "Trie",
    difficulty: "Hard",
    frequency: 4,
    companies: ["Amazon", "Google", "Meta"],
    tags: ["backtracking+trie", "hard"],
  },

  // ─── BIT MANIPULATION ───
  {
    id: "q102",
    title: "Number of 1 Bits",
    leetcodeId: 191,
    url: "https://leetcode.com/problems/number-of-1-bits/",
    topic: "Bit Manipulation",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["bit-ops"],
  },
  {
    id: "q103",
    title: "Counting Bits",
    leetcodeId: 338,
    url: "https://leetcode.com/problems/counting-bits/",
    topic: "Bit Manipulation",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["DP-bit"],
  },
  {
    id: "q104",
    title: "Reverse Bits",
    leetcodeId: 190,
    url: "https://leetcode.com/problems/reverse-bits/",
    topic: "Bit Manipulation",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Google", "Apple"],
    tags: ["bit-ops"],
  },
  {
    id: "q105",
    title: "Missing Number",
    leetcodeId: 268,
    url: "https://leetcode.com/problems/missing-number/",
    topic: "Bit Manipulation",
    pattern: "Bit Manipulation",
    difficulty: "Easy",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["XOR"],
  },
  {
    id: "q106",
    title: "Sum of Two Integers",
    leetcodeId: 371,
    url: "https://leetcode.com/problems/sum-of-two-integers/",
    topic: "Bit Manipulation",
    pattern: "Bit Manipulation",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google", "Microsoft"],
    tags: ["bit-ops"],
  },

  // ─── GREEDY ───
  {
    id: "q107",
    title: "Meeting Rooms II",
    leetcodeId: 253,
    url: "https://leetcode.com/problems/meeting-rooms-ii/",
    topic: "Greedy",
    pattern: "Heap / Priority Queue",
    difficulty: "Medium",
    frequency: 5,
    companies: ["Amazon", "Google", "Microsoft", "Meta", "Goldman Sachs"],
    tags: ["intervals", "must-do"],
  },
  {
    id: "q108",
    title: "Gas Station",
    leetcodeId: 134,
    url: "https://leetcode.com/problems/gas-station/",
    topic: "Greedy",
    pattern: "Greedy",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google"],
    tags: ["greedy-circular"],
  },
  {
    id: "q109",
    title: "Partition Labels",
    leetcodeId: 763,
    url: "https://leetcode.com/problems/partition-labels/",
    topic: "Greedy",
    pattern: "Greedy",
    difficulty: "Medium",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["greedy"],
  },

  // ─── MATH ───
  {
    id: "q110",
    title: "Pow(x,n)",
    leetcodeId: 50,
    url: "https://leetcode.com/problems/powx-n/",
    topic: "Math",
    pattern: "Recursion / Divide & Conquer",
    difficulty: "Medium",
    frequency: 4,
    companies: ["Amazon", "Google", "Microsoft", "Adobe"],
    tags: ["fast-exponentiation"],
  },
  {
    id: "q111",
    title: "Sqrt(x)",
    leetcodeId: 69,
    url: "https://leetcode.com/problems/sqrtx/",
    topic: "Math",
    pattern: "Binary Search",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Google"],
    tags: ["binary-search"],
  },
  {
    id: "q112",
    title: "Roman to Integer",
    leetcodeId: 13,
    url: "https://leetcode.com/problems/roman-to-integer/",
    topic: "Math",
    pattern: "Hashing",
    difficulty: "Easy",
    frequency: 3,
    companies: ["Amazon", "Microsoft", "Adobe"],
    tags: ["lookup-table"],
  },
];

// ── Helper: get questions for a company ──────────────────────────────────────
export function getQuestionsForCompany(company) {
  return QUESTIONS.filter((q) => q.companies.includes(company));
}

// ── Helper: group by pattern ─────────────────────────────────────────────────
export function groupByPattern(questions) {
  return questions.reduce((acc, q) => {
    if (!acc[q.pattern]) acc[q.pattern] = [];
    acc[q.pattern].push(q);
    return acc;
  }, {});
}

// ── Helper: sort by frequency desc ───────────────────────────────────────────
export function sortByFrequency(questions) {
  return [...questions].sort((a, b) => b.frequency - a.frequency);
}

// ── Helper: build day-wise plan ───────────────────────────────────────────────
// Returns array of { date, dayNum, questions[] }
export function buildDayPlan(
  company,
  daysLeft,
  questionsPerDay,
  startDate = new Date(),
) {
  const companyQs = sortByFrequency(getQuestionsForCompany(company));
  const days = [];
  let qIdx = 0;
  for (let d = 0; d < daysLeft; d++) {
    const date = new Date(startDate);
    date.setDate(date.getDate() + d);
    const dayQs = [];
    for (
      let q = 0;
      q < questionsPerDay && qIdx < companyQs.length;
      q++, qIdx++
    ) {
      dayQs.push(companyQs[qIdx]);
    }
    // Cycle if we run out
    if (dayQs.length === 0 && companyQs.length > 0) {
      qIdx = 0;
      for (
        let q = 0;
        q < questionsPerDay && qIdx < companyQs.length;
        q++, qIdx++
      ) {
        dayQs.push(companyQs[qIdx]);
      }
    }
    if (dayQs.length > 0) {
      days.push({
        dayNum: d + 1,
        date: date.toISOString().split("T")[0],
        questions: dayQs,
      });
    }
  }
  return days;
}
